# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-19 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171018_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_keys',
            new_name='work_years',
        ),
    ]
